### ISSUE TITLE
Allow agents that have name tags to be targettable

### ISSUE THREAD

**Issue by 3vcloud** [gwdevhub/GWToolboxpp#1035] opened 2024-04-23 21:18 UTC
Gadgets aren’t targetable on the minimap but in game you can target them using semi colon or clicking. Find the flag for name tag being visible and use that

**Comment by DubbleClick** [comment] 2024-04-25 09:46
Found that untargettable gadgets have no encrypted name.

**Comment by DubbleClick** [comment] 2024-04-25 16:31
duplicate of #1034 so closed

**Closed by DubbleClick** 2024-04-25 16:31 UTC
